### ISSUE TITLE
It doesn't compile anymore: ptr Seq is not a concrete type

### ISSUE THREAD

**Issue by Araq** [dom96/nim-opencv#2]

**Comment by severin-lemaignan** [comment]
I confirm the issue with `nim-0.10.2`.
Compilation fails with the following error:
```
$HOME/.nimble/pkgs/opencv-0.1.0/opencv/core.nim(1183, 33) Error: ')' expected
```

**Comment by v3ss0n** [comment]
so it won't work with latest version?

**Comment by dom96** [comment]
Compiling ``tests/camera.nim`` works perfectly fine for me on 0.12.1
