### ISSUE TITLE
Allow non-debugging win opencv dlls

### ISSUE THREAD

**Issue by jlp765** [dom96/nim-opencv#3]
definitions like
`coredll* = "(lib|)opencv_core(249|231)d.dll"`
be changed to
`coredll* = "(lib|)opencv_core(|249|231)(|d).dll"`

to allow `open_core.dll`  or `open_cored.dll`  or ....

---

Also,
do you have scripts that automate the c2nim conversion, so PRs for extra modules are pointless, 

or do you want PRs for some of the extra modules like `objdetect` that are not included yet in this package?

**Comment by dom96** [comment]
No scripts. But IIRC I didn't need to specify many flags.

Feel free to create PRs.

**Comment by jlp765** [comment]
fixed in PR #5
